### PR TITLE
Build for all target boards

### PR DESCRIPTION
**Pull request by paddatrapper**
Opsis, Atlys and FX2 dev board

### CODE REVIEW

**Comment by paddatrapper** [comment]
Travis seems to be having issue with the version.h git stuff again

**Comment by mithro** [comment]
We should really figure out what is going on with this version stuff - I started trying to debug it previously and it stopped happening :-(

I think we should use the environment matrix stuff so that it is quickly apparent which board is failing? See this example -> https://github.com/timvideos/HDMI2USB-litex-firmware/blob/master/.travis.yml

Otherwise maybe we should always build All versions and just have different output files? See the ixo-usb-jtag stuff maybe? https://github.com/mithro/ixo-usb-jtag/blob/master/Makefile

**Comment by paddatrapper** [comment]
@mithro, is this still an issue? I seem to remember seeing commits a while ago from you on this, but I'm not sure if they fixed it

**Comment by mithro** [comment]
Ignoring the git version issue. I still think this part of my comment is still relevant;

> I think we should use the environment matrix stuff so that it is quickly apparent which board is failing? See this example -> https://github.com/timvideos/HDMI2USB-litex-firmware/blob/master/.travis.yml
> 
> Otherwise maybe we should always build All versions and just have different output files? See the ixo-usb-jtag stuff maybe? https://github.com/mithro/ixo-usb-jtag/blob/master/Makefile

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/timvideos/HDMI2USB-litex-firmware">timvideos/HDMI2USB-litex-firmware</a></strong></div><div>HDMI2USB-litex-firmware - A version of the HDMI2USB firmware based around LiteX tools produced by @Enjoy-Digital (based on misoc+migen created by @M-Labs)</div></blockquote>
<blockquote><div> GitHub</div><div><strong><a href="https://github.com/mithro/ixo-usb-jtag">mithro/ixo-usb-jtag</a></strong></div><div>ixo-usb-jtag - usb-jtag - Altera USB Blaster Emulation with a FX2</div></blockquote>

**Comment by paddatrapper** [comment]
Ok. I'll take a look at those then and see what I can do

**Comment by paddatrapper** [comment]
It's now using a matrix to build. Once Travis finishes, this should be good to go

**Comment by mithro** [comment]
LGTM!

**Pull request merged**
